/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/lures": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List and search lures (Typesense-backed) */
        get: operations["listLures"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/lures/suggest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Autocomplete suggestions (instant search) */
        get: operations["suggestLures"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/lures/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lure detail page data */
        get: operations["getLure"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/lures/{slug}/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listReviews"];
        put?: never;
        post: operations["createReview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/favorites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listFavorites"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/favorites/{lureId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["addFavorite"];
        delete: operations["removeFavorite"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/inventory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listInventory"];
        put?: never;
        post: operations["addToInventory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/inventory/{entryId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteInventoryEntry"];
        options?: never;
        head?: never;
        patch: operations["updateInventoryEntry"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LureCard: {
            /** Format: uuid */
            id?: string;
            slug?: string;
            name?: string;
            brand?: string;
            lure_type?: string;
            water_type?: string;
            weight_g?: number;
            primary_image_url?: string;
            primary_color_hex?: string;
            target_species?: string[];
            price_avg_eur?: number;
            favorites_count?: number;
            /** @description null if unauthenticated */
            is_favorited?: boolean;
        };
        LureDetail: components["schemas"]["LureCard"] & {
            description?: string;
            length_mm?: number;
            depth_min_m?: number;
            depth_max_m?: number;
            hook_size?: string;
            hook_type?: string;
            hook_count?: number;
            material?: string;
            attributes?: Record<string, never>;
            colors?: {
                /** Format: uuid */
                id?: string;
                name?: string;
                hex_primary?: string;
                hex_secondary?: string;
                pattern?: string;
            }[];
            images?: {
                url?: string;
                /** Format: uuid */
                color_id?: string;
                is_primary?: boolean;
            }[];
            target_species_detail?: {
                slug?: string;
                common_name?: string;
                /** @enum {string} */
                confidence?: "primary" | "secondary";
            }[];
            pricing?: {
                avg_eur?: number;
                min_eur?: number;
                max_eur?: number;
                /** Format: date-time */
                updated_at?: string;
                retailers?: {
                    retailer?: string;
                    url?: string;
                    price_eur?: number;
                    in_stock?: boolean;
                }[];
            };
            avg_rating?: number;
            reviews_count?: number;
            /** @description null if unauthenticated */
            is_in_inventory?: boolean;
        };
        Review: {
            /** Format: uuid */
            id?: string;
            rating?: number;
            body?: string;
            helpful_count?: number;
            /** @description null if unauthenticated */
            is_helpful?: boolean;
            /** Format: date-time */
            created_at?: string;
            author?: {
                username?: string;
                avatar_url?: string;
            };
        };
        InventoryEntry: {
            /** Format: uuid */
            id?: string;
            lure?: components["schemas"]["LureCard"];
            color?: {
                /** Format: uuid */
                id?: string;
                name?: string;
                hex_primary?: string;
            };
            quantity?: number;
            /** @enum {string} */
            condition?: "new" | "good" | "used" | "lost";
            notes?: string;
            /** Format: date-time */
            added_at?: string;
        };
        CatalogFacets: {
            lure_types?: {
                value?: string;
                count?: number;
            }[];
            brands?: {
                value?: string;
                count?: number;
            }[];
            water_types?: {
                value?: string;
                count?: number;
            }[];
            species?: {
                value?: string;
                count?: number;
            }[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listLures: {
        parameters: {
            query?: {
                /** @description Full-text search query. Empty = list all. */
                q?: string;
                /** @example jig */
                lure_type?: string;
                water_type?: "freshwater" | "saltwater" | "both";
                /** @description Species slug. Multiple values comma-separated. */
                species?: string;
                /** @description Brand slug. */
                brand?: string;
                weight_min?: number;
                weight_max?: number;
                depth_min?: number;
                depth_max?: number;
                /** @default popularity */
                sort?: "popularity" | "price_asc" | "price_desc" | "newest";
                page?: number;
                per_page?: number;
                locale?: "pt" | "en" | "es";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated lure list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["LureCard"][];
                        meta?: {
                            total?: number;
                            page?: number;
                            per_page?: number;
                            facets?: components["schemas"]["CatalogFacets"];
                        };
                    };
                };
            };
        };
    };
    suggestLures: {
        parameters: {
            query: {
                q: string;
                locale?: "pt" | "en" | "es";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        suggestions?: {
                            slug?: string;
                            name?: string;
                            brand?: string;
                            type?: string;
                        }[];
                    };
                };
            };
        };
    };
    getLure: {
        parameters: {
            query?: {
                locale?: "pt" | "en" | "es";
            };
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LureDetail"];
                };
            };
            /** @description Lure not found or not published */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listReviews: {
        parameters: {
            query?: {
                sort?: "recent" | "helpful";
                page?: number;
            };
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["Review"][];
                        aggregate?: {
                            avg_rating?: number;
                            total_reviews?: number;
                            distribution?: {
                                1?: number;
                                2?: number;
                                3?: number;
                                4?: number;
                                5?: number;
                            };
                        };
                    };
                };
            };
        };
    };
    createReview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    rating: number;
                    body?: string;
                };
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Review"];
                };
            };
            /** @description User already reviewed this lure */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listFavorites: {
        parameters: {
            query?: {
                page?: number;
                per_page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["LureCard"][];
                        meta?: {
                            total?: number;
                        };
                    };
                };
            };
        };
    };
    addFavorite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lureId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Added */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Lure not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    removeFavorite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lureId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listInventory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["InventoryEntry"][];
                        total_unique_lures?: number;
                    };
                };
            };
        };
    };
    addToInventory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    lure_id: string;
                    /** Format: uuid */
                    color_id?: string;
                    /** @default 1 */
                    quantity?: number;
                    /** @enum {string} */
                    condition?: "new" | "good" | "used";
                    notes?: string;
                };
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InventoryEntry"];
                };
            };
            /** @description Entry already exists for this lure + color combination */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteInventoryEntry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entryId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not owner */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateInventoryEntry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entryId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    quantity?: number;
                    /** @enum {string} */
                    condition?: "new" | "good" | "used" | "lost";
                    notes?: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InventoryEntry"];
                };
            };
            /** @description Not owner */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
