/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/lures": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List and search lures (Typesense-backed) */
        get: operations["listLures"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/lures/suggest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Autocomplete suggestions (instant search) */
        get: operations["suggestLures"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/lures/{slug}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Lure detail page data */
        get: operations["getLure"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/sync": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Internal webhook (Supabase) — upserts a user on sign-up/sign-in
         * @description Called by the Supabase Auth webhook when a user is created or signs in. Idempotent: matches on (provider, provider_uid). Secured by the X-Webhook-Secret header (not user JWT).
         */
        post: operations["syncUser"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/auth/username": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Set the authenticated user's username (first OAuth sign-in) */
        post: operations["setUsername"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/users/{username}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Public profile (no PII — username, avatar, member since, counts) */
        get: operations["getPublicProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** RGPD account deletion (soft-delete, PII nullified, confirmation email) */
        delete: operations["deleteMyAccount"];
        options?: never;
        head?: never;
        /** Update own display name / avatar */
        patch: operations["updateMyProfile"];
        trace?: never;
    };
    "/v1/admin/brands": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a brand (admin) */
        post: operations["adminCreateBrand"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/species": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a species (admin) */
        post: operations["adminCreateSpecies"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/lures": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create a lure (admin) */
        post: operations["adminCreateLure"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/lures/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update a lure (admin) */
        patch: operations["adminUpdateLure"];
        trace?: never;
    };
    "/v1/admin/lures/{id}/prices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add a retailer price; recomputes price_6m_min/max/avg (admin) */
        post: operations["adminAddRetailerPrice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/admin/reviews/{reviewId}/moderation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Hide or show a review (admin) */
        patch: operations["adminModerateReview"];
        trace?: never;
    };
    "/v1/lures/{slug}/reviews": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listReviews"];
        put?: never;
        post: operations["createReview"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/lures/{slug}/reviews/{reviewId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteReview"];
        options?: never;
        head?: never;
        patch: operations["updateReview"];
        trace?: never;
    };
    "/v1/reviews/{reviewId}/helpful": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Toggle "helpful" vote on a review (one per user) */
        post: operations["toggleReviewHelpful"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/favorites": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listFavorites"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/favorites/{lureId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["addFavorite"];
        delete: operations["removeFavorite"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/inventory": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listInventory"];
        put?: never;
        post: operations["addToInventory"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/me/inventory/{entryId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteInventoryEntry"];
        options?: never;
        head?: never;
        patch: operations["updateInventoryEntry"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        LureCard: {
            /** Format: uuid */
            id?: string;
            slug?: string;
            name?: string;
            brand?: string;
            lure_type?: string;
            water_type?: string;
            weight_g?: number;
            primary_image_url?: string;
            primary_color_hex?: string;
            target_species?: string[];
            price_avg_eur?: number;
            favorites_count?: number;
            /** @description null if unauthenticated */
            is_favorited?: boolean;
        };
        LureDetail: components["schemas"]["LureCard"] & {
            description?: string;
            length_mm?: number;
            depth_min_m?: number;
            depth_max_m?: number;
            hook_size?: string;
            hook_type?: string;
            hook_count?: number;
            material?: string;
            attributes?: Record<string, never>;
            colors?: {
                /** Format: uuid */
                id?: string;
                name?: string;
                hex_primary?: string;
                hex_secondary?: string;
                pattern?: string;
            }[];
            images?: {
                url?: string;
                /** Format: uuid */
                color_id?: string;
                is_primary?: boolean;
            }[];
            target_species_detail?: {
                slug?: string;
                common_name?: string;
                /** @enum {string} */
                confidence?: "primary" | "secondary";
            }[];
            pricing?: {
                avg_eur?: number;
                min_eur?: number;
                max_eur?: number;
                /** Format: date-time */
                updated_at?: string;
                retailers?: {
                    retailer?: string;
                    url?: string;
                    price_eur?: number;
                    in_stock?: boolean;
                }[];
            };
            avg_rating?: number;
            reviews_count?: number;
            /** @description null if unauthenticated */
            is_in_inventory?: boolean;
        };
        Review: {
            /** Format: uuid */
            id?: string;
            rating?: number;
            body?: string;
            helpful_count?: number;
            /** @description null if unauthenticated */
            is_helpful?: boolean;
            /** Format: date-time */
            created_at?: string;
            author?: {
                username?: string;
                avatar_url?: string;
            };
        };
        InventoryEntry: {
            /** Format: uuid */
            id?: string;
            lure?: components["schemas"]["LureCard"];
            color?: {
                /** Format: uuid */
                id?: string;
                name?: string;
                hex_primary?: string;
            };
            quantity?: number;
            /** @enum {string} */
            condition?: "new" | "good" | "used" | "lost";
            notes?: string;
            /** Format: date-time */
            added_at?: string;
        };
        CatalogFacets: {
            lure_types?: {
                value?: string;
                count?: number;
            }[];
            brands?: {
                value?: string;
                count?: number;
            }[];
            water_types?: {
                value?: string;
                count?: number;
            }[];
            species?: {
                value?: string;
                count?: number;
            }[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listLures: {
        parameters: {
            query?: {
                /** @description Full-text search query. Empty = list all. */
                q?: string;
                /** @example jig */
                lure_type?: string;
                water_type?: "freshwater" | "saltwater" | "both";
                /** @description Species slug. Multiple values comma-separated. */
                species?: string;
                /** @description Brand slug. */
                brand?: string;
                weight_min?: number;
                weight_max?: number;
                depth_min?: number;
                depth_max?: number;
                /** @default popularity */
                sort?: "popularity" | "price_asc" | "price_desc" | "newest";
                page?: number;
                per_page?: number;
                locale?: "pt" | "en" | "es";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated lure list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["LureCard"][];
                        meta?: {
                            total?: number;
                            page?: number;
                            per_page?: number;
                            facets?: components["schemas"]["CatalogFacets"];
                        };
                    };
                };
            };
        };
    };
    suggestLures: {
        parameters: {
            query: {
                q: string;
                locale?: "pt" | "en" | "es";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        suggestions?: {
                            slug?: string;
                            name?: string;
                            brand?: string;
                            type?: string;
                        }[];
                    };
                };
            };
        };
    };
    getLure: {
        parameters: {
            query?: {
                locale?: "pt" | "en" | "es";
            };
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LureDetail"];
                };
            };
            /** @description Lure not found or not published */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    syncUser: {
        parameters: {
            query?: never;
            header?: {
                "X-Webhook-Secret"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @example google */
                    provider: string;
                    provider_uid: string;
                    email?: string;
                    display_name?: string;
                    avatar_url?: string;
                };
            };
        };
        responses: {
            /** @description User upserted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        user_id?: string;
                        username?: string;
                        needs_username?: boolean;
                    };
                };
            };
            /** @description Invalid webhook secret */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    setUsername: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    username: string;
                };
            };
        };
        responses: {
            /** @description Username set */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        username?: string;
                    };
                };
            };
            /** @description Username already taken */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Invalid username format */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getPublicProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                username: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        username?: string;
                        avatar_url?: string;
                        /** Format: date-time */
                        member_since?: string;
                        favorites_count?: number;
                        inventory_count?: number;
                        reviews_count?: number;
                    };
                };
            };
            /** @description User not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteMyAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Account scheduled for deletion */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateMyProfile: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    display_name?: string;
                    avatar_url?: string;
                };
            };
        };
        responses: {
            /** @description Updated */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    adminCreateBrand: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    slug: string;
                    name: string;
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not admin */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    adminCreateSpecies: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    slug: string;
                    /** @enum {string} */
                    water_type?: "freshwater" | "saltwater" | "both";
                    common_name: string;
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not admin */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    adminCreateLure: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    slug: string;
                    lure_type: string;
                    /** Format: uuid */
                    brand_id?: string;
                    name: string;
                    /** @enum {string} */
                    status?: "draft" | "published" | "archived";
                };
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not admin */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    adminUpdateLure: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    status?: "draft" | "published" | "archived";
                    weight_g?: number;
                };
            };
        };
        responses: {
            /** @description Updated */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not admin */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    adminAddRetailerPrice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    retailer: string;
                    url?: string;
                    price_eur: number;
                    in_stock?: boolean;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        price_6m_min_eur?: number;
                        price_6m_max_eur?: number;
                        price_6m_avg_eur?: number;
                    };
                };
            };
            /** @description Not admin */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    adminModerateReview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reviewId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    status: "published" | "hidden";
                };
            };
        };
        responses: {
            /** @description Updated */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not admin */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listReviews: {
        parameters: {
            query?: {
                sort?: "recent" | "helpful";
                page?: number;
            };
            header?: never;
            path: {
                slug: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["Review"][];
                        aggregate?: {
                            avg_rating?: number;
                            total_reviews?: number;
                            distribution?: {
                                1?: number;
                                2?: number;
                                3?: number;
                                4?: number;
                                5?: number;
                            };
                        };
                    };
                };
            };
        };
    };
    createReview: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    rating: number;
                    body?: string;
                };
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Review"];
                };
            };
            /** @description User already reviewed this lure */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteReview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
                reviewId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not the author */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateReview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                slug: string;
                reviewId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    rating?: number;
                    body?: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Review"];
                };
            };
            /** @description Not the author */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    toggleReviewHelpful: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                reviewId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        helpful_count?: number;
                        is_helpful?: boolean;
                    };
                };
            };
        };
    };
    listFavorites: {
        parameters: {
            query?: {
                page?: number;
                per_page?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["LureCard"][];
                        meta?: {
                            total?: number;
                        };
                    };
                };
            };
        };
    };
    addFavorite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lureId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Added */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Lure not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    removeFavorite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                lureId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Removed */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listInventory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        data?: components["schemas"]["InventoryEntry"][];
                        total_unique_lures?: number;
                    };
                };
            };
        };
    };
    addToInventory: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    lure_id: string;
                    /** Format: uuid */
                    color_id?: string;
                    /** @default 1 */
                    quantity?: number;
                    /** @enum {string} */
                    condition?: "new" | "good" | "used";
                    notes?: string;
                };
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InventoryEntry"];
                };
            };
            /** @description Entry already exists for this lure + color combination */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    deleteInventoryEntry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entryId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not owner */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateInventoryEntry: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                entryId: string;
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    quantity?: number;
                    /** @enum {string} */
                    condition?: "new" | "good" | "used" | "lost";
                    notes?: string;
                };
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InventoryEntry"];
                };
            };
            /** @description Not owner */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
}
