// <auto-generated />
using System;
using Infolure.Api.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Infolure.Api.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260613094203_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Infolure.Api.Infrastructure.Persistence.Entities.Brand", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.HasKey("Id")
                        .HasName("pk_brands");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_brands_slug");

                    b.ToTable("brands", (string)null);
                });

            modelBuilder.Entity("Infolure.Api.Infrastructure.Persistence.Entities.BrandTranslation", b =>
                {
                    b.Property<Guid>("BrandId")
                        .HasColumnType("uuid")
                        .HasColumnName("brand_id");

                    b.Property<string>("Locale")
                        .HasColumnType("text")
                        .HasColumnName("locale");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("BrandId", "Locale")
                        .HasName("pk_brand_translations");

                    b.ToTable("brand_translations", (string)null);
                });

            modelBuilder.Entity("Infolure.Api.Infrastructure.Persistence.Entities.Lure", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Attributes")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("attributes")
                        .HasDefaultValueSql("'{}'");

                    b.Property<Guid?>("BrandId")
                        .HasColumnType("uuid")
                        .HasColumnName("brand_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<decimal?>("DepthMaxM")
                        .HasColumnType("numeric")
                        .HasColumnName("depth_max_m");

                    b.Property<decimal?>("DepthMinM")
                        .HasColumnType("numeric")
                        .HasColumnName("depth_min_m");

                    b.Property<short?>("HookCount")
                        .HasColumnType("smallint")
                        .HasColumnName("hook_count");

                    b.Property<string>("HookSize")
                        .HasColumnType("text")
                        .HasColumnName("hook_size");

                    b.Property<string>("HookType")
                        .HasColumnType("text")
                        .HasColumnName("hook_type");

                    b.Property<decimal?>("LengthMm")
                        .HasColumnType("numeric")
                        .HasColumnName("length_mm");

                    b.Property<string>("LureType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("lure_type");

                    b.Property<string>("Material")
                        .HasColumnType("text")
                        .HasColumnName("material");

                    b.Property<string>("ModelRef")
                        .HasColumnType("text")
                        .HasColumnName("model_ref");

                    b.Property<decimal?>("Price6mAvgEur")
                        .HasColumnType("numeric")
                        .HasColumnName("price6m_avg_eur");

                    b.Property<decimal?>("Price6mMaxEur")
                        .HasColumnType("numeric")
                        .HasColumnName("price6m_max_eur");

                    b.Property<decimal?>("Price6mMinEur")
                        .HasColumnType("numeric")
                        .HasColumnName("price6m_min_eur");

                    b.Property<DateTimeOffset?>("Price6mUpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("price6m_updated_at");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("draft")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("WaterType")
                        .HasColumnType("text")
                        .HasColumnName("water_type");

                    b.Property<decimal?>("WeightG")
                        .HasColumnType("numeric")
                        .HasColumnName("weight_g");

                    b.HasKey("Id")
                        .HasName("pk_lures");

                    b.HasIndex("BrandId")
                        .HasDatabaseName("ix_lures_brand_id");

                    b.HasIndex("LureType")
                        .HasDatabaseName("ix_lures_lure_type");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_lures_slug");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_lures_status");

                    b.HasIndex("WaterType")
                        .HasDatabaseName("ix_lures_water_type");

                    b.HasIndex("WeightG")
                        .HasDatabaseName("ix_lures_weight_g");

                    b.ToTable("lures", null, t =>
                        {
                            t.HasCheckConstraint("ck_lure_status", "status IN ('draft','published','archived')");

                            t.HasCheckConstraint("ck_lure_water_type", "water_type IS NULL OR water_type IN ('freshwater','saltwater','both')");
                        });
                });

            modelBuilder.Entity("Infolure.Api.Infrastructure.Persistence.Entities.LureColor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("HexPrimary")
                        .HasColumnType("text")
                        .HasColumnName("hex_primary");

                    b.Property<string>("HexSecondary")
                        .HasColumnType("text")
                        .HasColumnName("hex_secondary");

                    b.Property<Guid>("LureId")
                        .HasColumnType("uuid")
                        .HasColumnName("lure_id");

                    b.Property<string>("NameEn")
                        .HasColumnType("text")
                        .HasColumnName("name_en");

                    b.Property<string>("NamePt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name_pt");

                    b.Property<string>("Pattern")
                        .HasColumnType("text")
                        .HasColumnName("pattern");

                    b.HasKey("Id")
                        .HasName("pk_lure_colors");

                    b.HasIndex("LureId")
                        .HasDatabaseName("ix_lure_colors_lure_id");

                    b.ToTable("lure_colors", (string)null);
                });

            modelBuilder.Entity("Infolure.Api.Infrastructure.Persistence.Entities.LureImage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ColorId")
                        .HasColumnType("uuid")
                        .HasColumnName("color_id");

                    b.Property<bool>("IsPrimary")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_primary");

                    b.Property<Guid>("LureId")
                        .HasColumnType("uuid")
                        .HasColumnName("lure_id");

                    b.Property<short>("SortOrder")
                        .HasColumnType("smallint")
                        .HasColumnName("sort_order");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_lure_images");

                    b.HasIndex("LureId")
                        .HasDatabaseName("ix_lure_images_lure_id");

                    b.ToTable("lure_images", (string)null);
                });

            modelBuilder.Entity("Infolure.Api.Infrastructure.Persistence.Entities.LureRetailerPrice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("InStock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("in_stock");

                    b.Property<Guid>("LureId")
                        .HasColumnType("uuid")
                        .HasColumnName("lure_id");

                    b.Property<decimal>("PriceEur")
                        .HasColumnType("numeric")
                        .HasColumnName("price_eur");

                    b.Property<string>("Retailer")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("retailer");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Url")
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("pk_lure_retailer_prices");

                    b.HasIndex("LureId")
                        .HasDatabaseName("ix_lure_retailer_prices_lure_id");

                    b.ToTable("lure_retailer_prices", null, t =>
                        {
                            t.HasCheckConstraint("ck_retailer_price_positive", "price_eur > 0");
                        });
                });

            modelBuilder.Entity("Infolure.Api.Infrastructure.Persistence.Entities.LureReview", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .HasColumnType("text")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<int>("HelpfulCount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("helpful_count");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("pt")
                        .HasColumnName("locale");

                    b.Property<Guid>("LureId")
                        .HasColumnType("uuid")
                        .HasColumnName("lure_id");

                    b.Property<short>("Rating")
                        .HasColumnType("smallint")
                        .HasColumnName("rating");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("published")
                        .HasColumnName("status");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_lure_reviews");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_lure_reviews_user_id");

                    b.HasIndex("LureId", "Status")
                        .HasDatabaseName("ix_lure_reviews_lure_id_status");

                    b.HasIndex("LureId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_lure_reviews_lure_id_user_id");

                    b.ToTable("lure_reviews", null, t =>
                        {
                            t.HasCheckConstraint("ck_review_body", "char_length(body) <= 1000");

                            t.HasCheckConstraint("ck_review_rating", "rating BETWEEN 1 AND 5");

                            t.HasCheckConstraint("ck_review_status", "status IN ('pending','published','hidden')");
                        });
                });

            modelBuilder.Entity("Infolure.Api.Infrastructure.Persistence.Entities.LureTargetSpecies", b =>
                {
                    b.Property<Guid>("LureId")
                        .HasColumnType("uuid")
                        .HasColumnName("lure_id");

                    b.Property<Guid>("SpeciesId")
                        .HasColumnType("uuid")
                        .HasColumnName("species_id");

                    b.Property<string>("Confidence")
                        .HasColumnType("text")
                        .HasColumnName("confidence");

                    b.HasKey("LureId", "SpeciesId")
                        .HasName("pk_lure_target_species");

                    b.HasIndex("SpeciesId")
                        .HasDatabaseName("ix_lure_target_species_species_id");

                    b.ToTable("lure_target_species", null, t =>
                        {
                            t.HasCheckConstraint("ck_target_confidence", "confidence IN ('primary','secondary')");
                        });
                });

            modelBuilder.Entity("Infolure.Api.Infrastructure.Persistence.Entities.LureTranslation", b =>
                {
                    b.Property<Guid>("LureId")
                        .HasColumnType("uuid")
                        .HasColumnName("lure_id");

                    b.Property<string>("Locale")
                        .HasColumnType("text")
                        .HasColumnName("locale");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.HasKey("LureId", "Locale")
                        .HasName("pk_lure_translations");

                    b.ToTable("lure_translations", (string)null);
                });

            modelBuilder.Entity("Infolure.Api.Infrastructure.Persistence.Entities.ReviewHelpfulVote", b =>
                {
                    b.Property<Guid>("ReviewId")
                        .HasColumnType("uuid")
                        .HasColumnName("review_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("ReviewId", "UserId")
                        .HasName("pk_review_helpful_votes");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_review_helpful_votes_user_id");

                    b.ToTable("review_helpful_votes", (string)null);
                });

            modelBuilder.Entity("Infolure.Api.Infrastructure.Persistence.Entities.Species", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Family")
                        .HasColumnType("text")
                        .HasColumnName("family");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("slug");

                    b.Property<string>("WaterType")
                        .HasColumnType("text")
                        .HasColumnName("water_type");

                    b.HasKey("Id")
                        .HasName("pk_species");

                    b.HasIndex("Slug")
                        .IsUnique()
                        .HasDatabaseName("ix_species_slug");

                    b.ToTable("species", null, t =>
                        {
                            t.HasCheckConstraint("ck_species_water_type", "water_type IN ('freshwater','saltwater','both')");
                        });
                });

            modelBuilder.Entity("Infolure.Api.Infrastructure.Persistence.Entities.SpeciesTranslation", b =>
                {
                    b.Property<Guid>("SpeciesId")
                        .HasColumnType("uuid")
                        .HasColumnName("species_id");

                    b.Property<string>("Locale")
                        .HasColumnType("text")
                        .HasColumnName("locale");

                    b.Property<string>("CommonName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("common_name");

                    b.HasKey("SpeciesId", "Locale")
                        .HasName("pk_species_translations");

                    b.ToTable("species_translations", (string)null);
                });

            modelBuilder.Entity("Infolure.Api.Infrastructure.Persistence.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text")
                        .HasColumnName("avatar_url");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.Property<DateTimeOffset?>("DeletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<string>("Locale")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("pt")
                        .HasColumnName("locale");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("user")
                        .HasColumnName("role");

                    b.Property<string>("Username")
                        .HasColumnType("text")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("pk_users");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasDatabaseName("ix_users_username");

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("ck_user_role", "role IN ('user','admin')");
                        });
                });

            modelBuilder.Entity("Infolure.Api.Infrastructure.Persistence.Entities.UserAuthProvider", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Email")
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<DateTimeOffset>("LinkedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("linked_at")
                        .HasDefaultValueSql("now()");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderUid")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("provider_uid");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_auth_providers");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_auth_providers_user_id");

                    b.HasIndex("Provider", "ProviderUid")
                        .IsUnique()
                        .HasDatabaseName("ix_user_auth_providers_provider_provider_uid");

                    b.ToTable("user_auth_providers", (string)null);
                });

            modelBuilder.Entity("Infolure.Api.Infrastructure.Persistence.Entities.UserLureFavorite", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("LureId")
                        .HasColumnType("uuid")
                        .HasColumnName("lure_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("now()");

                    b.HasKey("UserId", "LureId")
                        .HasName("pk_user_lure_favorites");

                    b.HasIndex("LureId")
                        .HasDatabaseName("ix_user_lure_favorites_lure_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_lure_favorites_user_id");

                    b.ToTable("user_lure_favorites", (string)null);
                });

            modelBuilder.Entity("Infolure.Api.Infrastructure.Persistence.Entities.UserLureInventory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("AddedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at")
                        .HasDefaultValueSql("now()");

                    b.Property<Guid?>("ColorId")
                        .HasColumnType("uuid")
                        .HasColumnName("color_id");

                    b.Property<string>("Condition")
                        .HasColumnType("text")
                        .HasColumnName("condition");

                    b.Property<Guid>("LureId")
                        .HasColumnType("uuid")
                        .HasColumnName("lure_id");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<short>("Quantity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("smallint")
                        .HasDefaultValue((short)1)
                        .HasColumnName("quantity");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_user_lure_inventory");

                    b.HasIndex("LureId")
                        .HasDatabaseName("ix_user_lure_inventory_lure_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_user_lure_inventory_user_id");

                    b.HasIndex("UserId", "LureId", "ColorId")
                        .IsUnique()
                        .HasDatabaseName("ix_user_lure_inventory_user_id_lure_id_color_id");

                    b.ToTable("user_lure_inventory", null, t =>
                        {
                            t.HasCheckConstraint("ck_inventory_condition", "condition IS NULL OR condition IN ('new','good','used','lost')");

                            t.HasCheckConstraint("ck_inventory_notes", "char_length(notes) <= 200");

                            t.HasCheckConstraint("ck_inventory_quantity", "quantity > 0");
                        });
                });

            modelBuilder.Entity("Infolure.Api.Infrastructure.Persistence.Entities.BrandTranslation", b =>
                {
                    b.HasOne("Infolure.Api.Infrastructure.Persistence.Entities.Brand", "Brand")
                        .WithMany("Translations")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_brand_translations_brands_brand_id");

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("Infolure.Api.Infrastructure.Persistence.Entities.Lure", b =>
                {
                    b.HasOne("Infolure.Api.Infrastructure.Persistence.Entities.Brand", "Brand")
                        .WithMany("Lures")
                        .HasForeignKey("BrandId")
                        .HasConstraintName("fk_lures_brands_brand_id");

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("Infolure.Api.Infrastructure.Persistence.Entities.LureColor", b =>
                {
                    b.HasOne("Infolure.Api.Infrastructure.Persistence.Entities.Lure", "Lure")
                        .WithMany("Colors")
                        .HasForeignKey("LureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lure_colors_lures_lure_id");

                    b.Navigation("Lure");
                });

            modelBuilder.Entity("Infolure.Api.Infrastructure.Persistence.Entities.LureImage", b =>
                {
                    b.HasOne("Infolure.Api.Infrastructure.Persistence.Entities.Lure", "Lure")
                        .WithMany("Images")
                        .HasForeignKey("LureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lure_images_lures_lure_id");

                    b.Navigation("Lure");
                });

            modelBuilder.Entity("Infolure.Api.Infrastructure.Persistence.Entities.LureRetailerPrice", b =>
                {
                    b.HasOne("Infolure.Api.Infrastructure.Persistence.Entities.Lure", "Lure")
                        .WithMany("RetailerPrices")
                        .HasForeignKey("LureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lure_retailer_prices_lures_lure_id");

                    b.Navigation("Lure");
                });

            modelBuilder.Entity("Infolure.Api.Infrastructure.Persistence.Entities.LureReview", b =>
                {
                    b.HasOne("Infolure.Api.Infrastructure.Persistence.Entities.Lure", "Lure")
                        .WithMany()
                        .HasForeignKey("LureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lure_reviews_lures_lure_id");

                    b.HasOne("Infolure.Api.Infrastructure.Persistence.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_lure_reviews_users_user_id");

                    b.Navigation("Lure");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Infolure.Api.Infrastructure.Persistence.Entities.LureTargetSpecies", b =>
                {
                    b.HasOne("Infolure.Api.Infrastructure.Persistence.Entities.Lure", "Lure")
                        .WithMany("TargetSpecies")
                        .HasForeignKey("LureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lure_target_species_lures_lure_id");

                    b.HasOne("Infolure.Api.Infrastructure.Persistence.Entities.Species", "Species")
                        .WithMany()
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lure_target_species_species_species_id");

                    b.Navigation("Lure");

                    b.Navigation("Species");
                });

            modelBuilder.Entity("Infolure.Api.Infrastructure.Persistence.Entities.LureTranslation", b =>
                {
                    b.HasOne("Infolure.Api.Infrastructure.Persistence.Entities.Lure", "Lure")
                        .WithMany("Translations")
                        .HasForeignKey("LureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lure_translations_lures_lure_id");

                    b.Navigation("Lure");
                });

            modelBuilder.Entity("Infolure.Api.Infrastructure.Persistence.Entities.ReviewHelpfulVote", b =>
                {
                    b.HasOne("Infolure.Api.Infrastructure.Persistence.Entities.LureReview", "Review")
                        .WithMany("HelpfulVotes")
                        .HasForeignKey("ReviewId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_review_helpful_votes_lure_reviews_review_id");

                    b.HasOne("Infolure.Api.Infrastructure.Persistence.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_review_helpful_votes_users_user_id");

                    b.Navigation("Review");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Infolure.Api.Infrastructure.Persistence.Entities.SpeciesTranslation", b =>
                {
                    b.HasOne("Infolure.Api.Infrastructure.Persistence.Entities.Species", "Species")
                        .WithMany("Translations")
                        .HasForeignKey("SpeciesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_species_translations_species_species_id");

                    b.Navigation("Species");
                });

            modelBuilder.Entity("Infolure.Api.Infrastructure.Persistence.Entities.UserAuthProvider", b =>
                {
                    b.HasOne("Infolure.Api.Infrastructure.Persistence.Entities.User", "User")
                        .WithMany("AuthProviders")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_auth_providers_users_user_id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Infolure.Api.Infrastructure.Persistence.Entities.UserLureFavorite", b =>
                {
                    b.HasOne("Infolure.Api.Infrastructure.Persistence.Entities.Lure", "Lure")
                        .WithMany()
                        .HasForeignKey("LureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_lure_favorites_lures_lure_id");

                    b.HasOne("Infolure.Api.Infrastructure.Persistence.Entities.User", "User")
                        .WithMany("Favorites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_lure_favorites_users_user_id");

                    b.Navigation("Lure");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Infolure.Api.Infrastructure.Persistence.Entities.UserLureInventory", b =>
                {
                    b.HasOne("Infolure.Api.Infrastructure.Persistence.Entities.Lure", "Lure")
                        .WithMany()
                        .HasForeignKey("LureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_lure_inventory_lures_lure_id");

                    b.HasOne("Infolure.Api.Infrastructure.Persistence.Entities.User", "User")
                        .WithMany("Inventory")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_lure_inventory_users_user_id");

                    b.Navigation("Lure");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Infolure.Api.Infrastructure.Persistence.Entities.Brand", b =>
                {
                    b.Navigation("Lures");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Infolure.Api.Infrastructure.Persistence.Entities.Lure", b =>
                {
                    b.Navigation("Colors");

                    b.Navigation("Images");

                    b.Navigation("RetailerPrices");

                    b.Navigation("TargetSpecies");

                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Infolure.Api.Infrastructure.Persistence.Entities.LureReview", b =>
                {
                    b.Navigation("HelpfulVotes");
                });

            modelBuilder.Entity("Infolure.Api.Infrastructure.Persistence.Entities.Species", b =>
                {
                    b.Navigation("Translations");
                });

            modelBuilder.Entity("Infolure.Api.Infrastructure.Persistence.Entities.User", b =>
                {
                    b.Navigation("AuthProviders");

                    b.Navigation("Favorites");

                    b.Navigation("Inventory");
                });
#pragma warning restore 612, 618
        }
    }
}
